FROM python:3.12-slim

WORKDIR /app

COPY backend_requirements.txt ./
RUN pip install --no-cache-dir -r backend_requirements.txt

COPY backend ./backend
COPY grimoire ./grimoire

EXPOSE 5000
CMD ["python", "backend/app.py"]
