services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - APP_HOST=0.0.0.0
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
